Launch SetupWizard directly after NFC provisioning
PS: Change to wait ProvisioningActivity finishing because
new error due to IntentTestRule
java.lang.IllegalStateException: #init was called twice in a row. Make
sure to call #release after every #init

Bug: 29829689
Test: runtest managed-provisioning
Change-Id: I98a5b38beb8f0fbb3613fdc1689de31525a207f3